guardrails:
  - name: prompt_injection
    threshold: ">= 0.7"
  - name: toxic
    threshold: "0.7"
  - name: jail_break
    threshold: ">= 1.0"
  - name: biased
    threshold: "0.8"
  - name: harmful
