guardrails:
  - name: prompt_injection
  - name: toxic
  - name: jail_break
  - name: biased
  - name: harmful
  - name: modality
  - name: language
  - name: pii_detector
  - name: secrets_detector
  - name: malicious_url
