workflowVersion: 1.0.0
speakeasyVersion: 1.520.0
sources:
    Acuvity-OAS:
        inputs:
            - location: ./apex-openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/acuvity/acuvity/acuvity-oas
targets:
    python:
        target: python
        source: Acuvity-OAS
        output: .
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/acuvity/acuvity/acuvity-oas-python-code-samples
            blocking: false
