"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DestinationTypedDict(TypedDict):
    r"""Represents the destination that this request was made to."""

    app: NotRequired[str]
    r"""The name of the application that the domain belongs to."""
    component: NotRequired[str]
    r"""The component of the application that the domain belongs to."""
    host: NotRequired[str]
    r"""The host name of the request. Optional, matching the destination of a scan or
    police request: the caller may omit it, and it is only filled in when the
    resolved provider or app component declares a host of its own.
    """
    ip: NotRequired[str]
    r"""The destination IP address of the request."""
    labels: NotRequired[List[str]]
    r"""The list of labels attached to the application request destination."""
    workload_group_hash: NotRequired[str]
    r"""The hash of the workload group this application belongs to."""
    workload_group_label: NotRequired[str]
    r"""The label format of the workload group this application belongs to."""
    workload_group_set_hash: NotRequired[str]
    r"""The hash of the workload group set this application belongs to."""
    workload_group_set_label: NotRequired[str]
    r"""The label format of the workload group set this application belongs to."""


class Destination(BaseModel):
    r"""Represents the destination that this request was made to."""

    app: Optional[str] = None
    r"""The name of the application that the domain belongs to."""

    component: Optional[str] = None
    r"""The component of the application that the domain belongs to."""

    host: Optional[str] = None
    r"""The host name of the request. Optional, matching the destination of a scan or
    police request: the caller may omit it, and it is only filled in when the
    resolved provider or app component declares a host of its own.
    """

    ip: Optional[str] = None
    r"""The destination IP address of the request."""

    labels: Optional[List[str]] = None
    r"""The list of labels attached to the application request destination."""

    workload_group_hash: Annotated[
        Optional[str], pydantic.Field(alias="workloadGroupHash")
    ] = None
    r"""The hash of the workload group this application belongs to."""

    workload_group_label: Annotated[
        Optional[str], pydantic.Field(alias="workloadGroupLabel")
    ] = None
    r"""The label format of the workload group this application belongs to."""

    workload_group_set_hash: Annotated[
        Optional[str], pydantic.Field(alias="workloadGroupSetHash")
    ] = None
    r"""The hash of the workload group set this application belongs to."""

    workload_group_set_label: Annotated[
        Optional[str], pydantic.Field(alias="workloadGroupSetLabel")
    ] = None
    r"""The label format of the workload group set this application belongs to."""
