"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DetectorTypedDict(TypedDict):
    r"""Represent a detector an analyzer can use."""

    description: NotRequired[str]
    r"""The description of the detection."""
    friendly_name: NotRequired[str]
    r"""The friendly name of the detection."""
    group: NotRequired[str]
    r"""The group the detection belongs to."""
    label: NotRequired[str]
    r"""The label returned by the model."""
    name: NotRequired[str]
    r"""The name of the detection."""
    positional: NotRequired[bool]
    r"""Tell if the detection is positional."""


class Detector(BaseModel):
    r"""Represent a detector an analyzer can use."""

    description: Optional[str] = None
    r"""The description of the detection."""

    friendly_name: Annotated[Optional[str], pydantic.Field(alias="friendlyName")] = None
    r"""The friendly name of the detection."""

    group: Optional[str] = None
    r"""The group the detection belongs to."""

    label: Optional[str] = None
    r"""The label returned by the model."""

    name: Optional[str] = None
    r"""The name of the detection."""

    positional: Optional[bool] = None
    r"""Tell if the detection is positional."""
