"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
from enum import Enum
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class Confidence(str, Enum):
    r"""The detection confidence level to operate on."""

    UNLIKELY = "Unlikely"
    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"


class Operator(str, Enum):
    r"""Specifies how to compare the detection's confidence value against the matcher's
    threshold:
    - 'Is': All Detections confidence must exactly match the threshold
    - 'Min': At least one detection confidence must be greater than or equal to the
    threshold
    - 'Max': At least one detection confidence must be less than the threshold
    The default value is 'Min'.
    """

    IS = "Is"
    MIN = "Min"
    MAX = "Max"


class DetectionmatcherTypedDict(TypedDict):
    r"""Represent a detection matcher.
    A Detection Matcher serves as a filtering mechanism for analyzers, determining
    which detections should trigger an analysis. It allows for flexible pattern
    matching on detection attributes such as name, label, and group using glob-style
    wildcards. Additionally, it enables confidence-based filtering by defining
    thresholds and comparison operators. Detection Matchers provide a structured way
    to control when and how analyzers engage with incoming detections.
    """

    confidence: NotRequired[Confidence]
    r"""The detection confidence level to operate on."""
    description: NotRequired[str]
    r"""The description of the detection matcher."""
    group: NotRequired[str]
    r"""The group pattern used to match detection group. Supports glob-style wildcards
    (e.g. 'Text*' matches 'Text', 'Text_'). Default value is '*' meaning matching
    any
    detection group.
    """
    label: NotRequired[str]
    r"""The label pattern used to match detection label. Supports glob-style wildcards
    (e.g. 'txt*' matches 'txt', 'txtuf8'). Default value is '*' meaning matching any
    detection label.
    """
    name: NotRequired[str]
    r"""The name pattern used to match detection name. Supports glob-style wildcards
    (e.g. 'txt*' matches 'txt', 'txtuf8'). Default value is '*' meaning matching any
    detection name.
    """
    operator: NotRequired[Operator]
    r"""Specifies how to compare the detection's confidence value against the matcher's
    threshold:
    - 'Is': All Detections confidence must exactly match the threshold
    - 'Min': At least one detection confidence must be greater than or equal to the
    threshold
    - 'Max': At least one detection confidence must be less than the threshold
    The default value is 'Min'.
    """


class Detectionmatcher(BaseModel):
    r"""Represent a detection matcher.
    A Detection Matcher serves as a filtering mechanism for analyzers, determining
    which detections should trigger an analysis. It allows for flexible pattern
    matching on detection attributes such as name, label, and group using glob-style
    wildcards. Additionally, it enables confidence-based filtering by defining
    thresholds and comparison operators. Detection Matchers provide a structured way
    to control when and how analyzers engage with incoming detections.
    """

    confidence: Optional[Confidence] = None
    r"""The detection confidence level to operate on."""

    description: Optional[str] = None
    r"""The description of the detection matcher."""

    group: Optional[str] = "*"
    r"""The group pattern used to match detection group. Supports glob-style wildcards
    (e.g. 'Text*' matches 'Text', 'Text_'). Default value is '*' meaning matching
    any
    detection group.
    """

    label: Optional[str] = "*"
    r"""The label pattern used to match detection label. Supports glob-style wildcards
    (e.g. 'txt*' matches 'txt', 'txtuf8'). Default value is '*' meaning matching any
    detection label.
    """

    name: Optional[str] = "*"
    r"""The name pattern used to match detection name. Supports glob-style wildcards
    (e.g. 'txt*' matches 'txt', 'txtuf8'). Default value is '*' meaning matching any
    detection name.
    """

    operator: Optional[Operator] = Operator.MIN
    r"""Specifies how to compare the detection's confidence value against the matcher's
    threshold:
    - 'Is': All Detections confidence must exactly match the threshold
    - 'Min': At least one detection confidence must be greater than or equal to the
    threshold
    - 'Max': At least one detection confidence must be less than the threshold
    The default value is 'Min'.
    """
