"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .toolresult import Toolresult, ToolresultTypedDict
from .tooluse import Tooluse, TooluseTypedDict
from acuvity.types import BaseModel
from enum import Enum
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Kind(str, Enum):
    r"""The kind of content carried by this extraction. Used together with role to
    label what the extracted blob represents so the UI can render it correctly and
    analyzers can dispatch appropriately:
    - Message: free-form natural language (default).
    - Thinking: model reasoning trace (e.g. Anthropic thinking, OpenAI reasoning,
    Gemini thought).
    - ToolDefinition: tool/function schema advertised to the model (name,
    description, JSON schema).
    - ToolInput: structured arguments the model passes when invoking a tool.
    - ToolOutput: result returned to the model after a tool call.
    - File: uploaded or attached file payload.
    - Resource: externally-supplied context injected into the prompt (RAG
    document, search result, MCP resource).
    - Event: control or lifecycle marker with no analyzable content.
    """

    MESSAGE = "Message"
    THINKING = "Thinking"
    TOOL_DEFINITION = "ToolDefinition"
    TOOL_INPUT = "ToolInput"
    TOOL_OUTPUT = "ToolOutput"
    FILE = "File"
    RESOURCE = "Resource"
    EVENT = "Event"


class Role(str, Enum):
    r"""The role of the message represented by this extraction."""

    USER = "User"
    ASSISTANT = "Assistant"
    SYSTEM = "System"
    TOOL = "Tool"


class ExtractionrequestTypedDict(TypedDict):
    r"""Represents the extraction that the user wants to extract."""

    annotations: NotRequired[Dict[str, str]]
    r"""Annotations attached to the extraction."""
    data: NotRequired[str]
    r"""The binary data to request extraction for."""
    internal: NotRequired[bool]
    r"""If true, this extraction is for internal use only. This can be used by agentic
    systems to mark an extraction as internal only as opposed to user facing.
    """
    is_file: NotRequired[bool]
    r"""If true, the data of the extraction is a file."""
    is_stored: NotRequired[bool]
    r"""If true, indicates that the file has been stored."""
    kind: NotRequired[Kind]
    r"""The kind of content carried by this extraction. Used together with role to
    label what the extracted blob represents so the UI can render it correctly and
    analyzers can dispatch appropriately:
    - Message: free-form natural language (default).
    - Thinking: model reasoning trace (e.g. Anthropic thinking, OpenAI reasoning,
    Gemini thought).
    - ToolDefinition: tool/function schema advertised to the model (name,
    description, JSON schema).
    - ToolInput: structured arguments the model passes when invoking a tool.
    - ToolOutput: result returned to the model after a tool call.
    - File: uploaded or attached file payload.
    - Resource: externally-supplied context injected into the prompt (RAG
    document, search result, MCP resource).
    - Event: control or lifecycle marker with no analyzable content.
    """
    label: NotRequired[str]
    r"""Contains events and other information that are not actual user content, and will
    not go through analysis.
    """
    role: NotRequired[Role]
    r"""The role of the message represented by this extraction."""
    tool_results: NotRequired[List[ToolresultTypedDict]]
    r"""Tool call results which are passed in to this request."""
    tool_uses: NotRequired[List[TooluseTypedDict]]
    r"""Tool uses as requested by a model."""


class Extractionrequest(BaseModel):
    r"""Represents the extraction that the user wants to extract."""

    annotations: Optional[Dict[str, str]] = None
    r"""Annotations attached to the extraction."""

    data: Optional[str] = None
    r"""The binary data to request extraction for."""

    internal: Optional[bool] = None
    r"""If true, this extraction is for internal use only. This can be used by agentic
    systems to mark an extraction as internal only as opposed to user facing.
    """

    is_file: Annotated[Optional[bool], pydantic.Field(alias="isFile")] = None
    r"""If true, the data of the extraction is a file."""

    is_stored: Annotated[Optional[bool], pydantic.Field(alias="isStored")] = None
    r"""If true, indicates that the file has been stored."""

    kind: Optional[Kind] = Kind.MESSAGE
    r"""The kind of content carried by this extraction. Used together with role to
    label what the extracted blob represents so the UI can render it correctly and
    analyzers can dispatch appropriately:
    - Message: free-form natural language (default).
    - Thinking: model reasoning trace (e.g. Anthropic thinking, OpenAI reasoning,
    Gemini thought).
    - ToolDefinition: tool/function schema advertised to the model (name,
    description, JSON schema).
    - ToolInput: structured arguments the model passes when invoking a tool.
    - ToolOutput: result returned to the model after a tool call.
    - File: uploaded or attached file payload.
    - Resource: externally-supplied context injected into the prompt (RAG
    document, search result, MCP resource).
    - Event: control or lifecycle marker with no analyzable content.
    """

    label: Optional[str] = None
    r"""Contains events and other information that are not actual user content, and will
    not go through analysis.
    """

    role: Optional[Role] = Role.USER
    r"""The role of the message represented by this extraction."""

    tool_results: Annotated[
        Optional[List[Toolresult]], pydantic.Field(alias="toolResults")
    ] = None
    r"""Tool call results which are passed in to this request."""

    tool_uses: Annotated[Optional[List[Tooluse]], pydantic.Field(alias="toolUses")] = (
        None
    )
    r"""Tool uses as requested by a model."""
