"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RequestdestinationTypedDict(TypedDict):
    r"""RequestDestination holds the destination information for a request. When app
    and component are set, the request is evaluated against the app component's
    policies instead of a provider. In that case, the provider field must not be
    set.
    On the police API an egress request must name its target, so app and component
    are required unless a provider is given. On the scan API they may be left out
    to run a plain scan that targets nothing.
    """

    app: NotRequired[str]
    r"""The name of the destination application. Only takes effect together with
    component: setting one without the other counts as no destination at all.
    """
    component: NotRequired[str]
    r"""The component of the destination application. Only takes effect together with
    app: setting one without the other counts as no destination at all.
    """
    host: NotRequired[str]
    r"""The host name of the destination. Optional, for logging enrichment."""
    ip: NotRequired[str]
    r"""The destination IP address. Optional, for logging enrichment."""
    port: NotRequired[int]
    r"""The destination port of the request. Optional: when it is not set, 443 is
    assumed. It is made available to policies as destinationPort.
    """


class Requestdestination(BaseModel):
    r"""RequestDestination holds the destination information for a request. When app
    and component are set, the request is evaluated against the app component's
    policies instead of a provider. In that case, the provider field must not be
    set.
    On the police API an egress request must name its target, so app and component
    are required unless a provider is given. On the scan API they may be left out
    to run a plain scan that targets nothing.
    """

    app: Optional[str] = None
    r"""The name of the destination application. Only takes effect together with
    component: setting one without the other counts as no destination at all.
    """

    component: Optional[str] = None
    r"""The component of the destination application. Only takes effect together with
    app: setting one without the other counts as no destination at all.
    """

    host: Optional[str] = None
    r"""The host name of the destination. Optional, for logging enrichment."""

    ip: Optional[str] = None
    r"""The destination IP address. Optional, for logging enrichment."""

    port: Optional[int] = None
    r"""The destination port of the request. Optional: when it is not set, 443 is
    assumed. It is made available to policies as destinationPort.
    """
