"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class RequestsourceTypedDict(TypedDict):
    r"""RequestSource holds the information about where a request originates from. On
    egress, the source is the app component the caller's token identifies, and this
    only carries optional enrichment. On ingress, the source is whoever is calling
    into that app component, and the token field identifies it.
    The username and userClaims are only used when no token is given, or when the
    given token carries no user identity of its own: identity derived from a
    validated token always wins over identity asserted in the request body.
    """

    ip: NotRequired[str]
    r"""The source IP address of the request. Optional, for logging enrichment."""
    token: NotRequired[str]
    r"""A valid token identifying the source of the request. Only applicable when the
    direction is Ingress. This can either be a component token, in which case the
    request principal is populated with the source app and component identity, or
    a token issued for an application component OAuth client, in which case the
    source app and component as well as the user identity are both derived from
    it.
    """
    user_claims: NotRequired[List[str]]
    r"""The optional user claims of the request. This can be an incomplete list, and
    claims can be mapped to different keys.
    """
    username: NotRequired[str]
    r"""The optional username of the request."""


class Requestsource(BaseModel):
    r"""RequestSource holds the information about where a request originates from. On
    egress, the source is the app component the caller's token identifies, and this
    only carries optional enrichment. On ingress, the source is whoever is calling
    into that app component, and the token field identifies it.
    The username and userClaims are only used when no token is given, or when the
    given token carries no user identity of its own: identity derived from a
    validated token always wins over identity asserted in the request body.
    """

    ip: Optional[str] = None
    r"""The source IP address of the request. Optional, for logging enrichment."""

    token: Optional[str] = None
    r"""A valid token identifying the source of the request. Only applicable when the
    direction is Ingress. This can either be a component token, in which case the
    request principal is populated with the source app and component identity, or
    a token issued for an application component OAuth client, in which case the
    source app and component as well as the user identity are both derived from
    it.
    """

    user_claims: Annotated[Optional[List[str]], pydantic.Field(alias="userClaims")] = (
        None
    )
    r"""The optional user claims of the request. This can be an incomplete list, and
    claims can be mapped to different keys.
    """

    username: Optional[str] = None
    r"""The optional username of the request."""
