"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
from enum import Enum
import pydantic
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Direction(str, Enum):
    r"""The direction of the traffic for this request. Determines whether ingress or
    egress policies are evaluated for the app component.
    """

    EGRESS = "Egress"
    INGRESS = "Ingress"


class RequestappTypedDict(TypedDict):
    r"""RequestApp holds the application processing information for a request. For
    police requests in an apps namespace, this is required when using an AppToken.
    When using a ComponentToken, the app and component are inferred from the token
    claims; if provided, they must match. For scan requests, this is optional and
    enhances logging with app/component context.
    """

    component: str
    r"""The name of the component."""
    name: str
    r"""The name of the application."""
    ip: NotRequired[str]
    r"""The source IP address of the request."""
    direction: NotRequired[Direction]
    r"""The direction of the traffic for this request. Determines whether ingress or
    egress policies are evaluated for the app component.
    """
    ingress_source_token: NotRequired[str]
    r"""A valid component token representing the source application component for
    ingress requests. When set, it will be validated and used to populate the
    request principal with the source app/component identity. Only applicable
    when the direction is Ingress.
    """
    port: NotRequired[int]
    r"""The port of the ingress listener for this request. Required when direction
    is Ingress to select the correct listener configuration. Mirrors the
    X-Acuvity-Ingress-Port header used by the cloud-apex agent.
    """
    user_claims: NotRequired[List[str]]
    r"""The optional user claims of the request. This can be an incomplete list, and
    claims can be mapped to different keys.
    """
    username: NotRequired[str]
    r"""The optional username of the request."""


class Requestapp(BaseModel):
    r"""RequestApp holds the application processing information for a request. For
    police requests in an apps namespace, this is required when using an AppToken.
    When using a ComponentToken, the app and component are inferred from the token
    claims; if provided, they must match. For scan requests, this is optional and
    enhances logging with app/component context.
    """

    component: str
    r"""The name of the component."""

    name: str
    r"""The name of the application."""

    ip: Annotated[Optional[str], pydantic.Field(alias="IP")] = None
    r"""The source IP address of the request."""

    direction: Optional[Direction] = Direction.EGRESS
    r"""The direction of the traffic for this request. Determines whether ingress or
    egress policies are evaluated for the app component.
    """

    ingress_source_token: Annotated[
        Optional[str], pydantic.Field(alias="ingressSourceToken")
    ] = None
    r"""A valid component token representing the source application component for
    ingress requests. When set, it will be validated and used to populate the
    request principal with the source app/component identity. Only applicable
    when the direction is Ingress.
    """

    port: Optional[int] = None
    r"""The port of the ingress listener for this request. Required when direction
    is Ingress to select the correct listener configuration. Mirrors the
    X-Acuvity-Ingress-Port header used by the cloud-apex agent.
    """

    user_claims: Annotated[Optional[List[str]], pydantic.Field(alias="userClaims")] = (
        None
    )
    r"""The optional user claims of the request. This can be an incomplete list, and
    claims can be mapped to different keys.
    """

    username: Optional[str] = None
    r"""The optional username of the request."""
