"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RequestdestinationTypedDict(TypedDict):
    r"""RequestDestination holds the destination information for a request. When app
    and component are set, the request is evaluated against the app component's
    policies instead of a provider. In that case, the provider field must not be
    set.
    """

    app: NotRequired[str]
    r"""The name of the destination application."""
    component: NotRequired[str]
    r"""The component of the destination application."""
    host: NotRequired[str]
    r"""The host name of the destination. Optional, for logging enrichment."""
    ip: NotRequired[str]
    r"""The destination IP address. Optional, for logging enrichment."""


class Requestdestination(BaseModel):
    r"""RequestDestination holds the destination information for a request. When app
    and component are set, the request is evaluated against the app component's
    policies instead of a provider. In that case, the provider field must not be
    set.
    """

    app: Optional[str] = None
    r"""The name of the destination application."""

    component: Optional[str] = None
    r"""The component of the destination application."""

    host: Optional[str] = None
    r"""The host name of the destination. Optional, for logging enrichment."""

    ip: Optional[str] = None
    r"""The destination IP address. Optional, for logging enrichment."""
