"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
from enum import Enum
import pydantic
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PreviousDecision(str, Enum):
    r"""The decision produced before the failClose or failOpen mutation
    flipped it. Set only when the user-facing Decision is the result
    of a platform-error override, so the audit log can surface what
    the policy would have decided otherwise.
    """

    DENY = "Deny"
    ALLOW = "Allow"
    ASK = "Ask"
    REPORT = "Report"
    BYPASSED = "Bypassed"
    FORBIDDEN_USER = "ForbiddenUser"
    SKIPPED = "Skipped"
    REDIRECTED = "Redirected"
    NOT_APPLICABLE = "NotApplicable"


class Stage(str, Enum):
    r"""The pipeline component that produced the error. Combined with the
    Type axis on the parent round-trip (Input/Output) and the Offband
    flag, gives the full discrimination of where a platform/upstream
    failure originated. Each value maps to an ownership tier:
    Proofpoint AI Security-owned (Extraction, Analysis, AssignPolicy, AccessPolicy),
    customer-owned (ContentPolicy), provider-owned (Upstream).
    """

    EXTRACTION = "Extraction"
    ANALYSIS = "Analysis"
    CONTENT_POLICY = "ContentPolicy"
    ASSIGN_POLICY = "AssignPolicy"
    ACCESS_POLICY = "AccessPolicy"
    UPSTREAM = "Upstream"


class RoundtriperrorType(str, Enum):
    r"""The source of the failure. PlatformError covers apex-side stages
    (Extraction, Analysis, ContentPolicy, AccessPolicy). UpstreamError
    covers anything attributable to the upstream provider (transport
    failures or non-2xx HTTP responses).
    """

    PLATFORM_ERROR = "PlatformError"
    UPSTREAM_ERROR = "UpstreamError"


class RoundtriperrorTypedDict(TypedDict):
    r"""Structured error info attached to a roundtrip when a non-user-facing
    platform stage or the upstream provider failed. Carries the platform-side
    detail (type, stage, message) for debugging and provider-health
    derivation. The Decision field still reflects the policy/processing
    outcome per existing semantics.
    """

    message: NotRequired[str]
    r"""Human-readable error message."""
    previous_decision: NotRequired[PreviousDecision]
    r"""The decision produced before the failClose or failOpen mutation
    flipped it. Set only when the user-facing Decision is the result
    of a platform-error override, so the audit log can surface what
    the policy would have decided otherwise.
    """
    stage: NotRequired[Stage]
    r"""The pipeline component that produced the error. Combined with the
    Type axis on the parent round-trip (Input/Output) and the Offband
    flag, gives the full discrimination of where a platform/upstream
    failure originated. Each value maps to an ownership tier:
    Proofpoint AI Security-owned (Extraction, Analysis, AssignPolicy, AccessPolicy),
    customer-owned (ContentPolicy), provider-owned (Upstream).
    """
    type: NotRequired[RoundtriperrorType]
    r"""The source of the failure. PlatformError covers apex-side stages
    (Extraction, Analysis, ContentPolicy, AccessPolicy). UpstreamError
    covers anything attributable to the upstream provider (transport
    failures or non-2xx HTTP responses).
    """


class Roundtriperror(BaseModel):
    r"""Structured error info attached to a roundtrip when a non-user-facing
    platform stage or the upstream provider failed. Carries the platform-side
    detail (type, stage, message) for debugging and provider-health
    derivation. The Decision field still reflects the policy/processing
    outcome per existing semantics.
    """

    message: Optional[str] = None
    r"""Human-readable error message."""

    previous_decision: Annotated[
        Optional[PreviousDecision], pydantic.Field(alias="previousDecision")
    ] = None
    r"""The decision produced before the failClose or failOpen mutation
    flipped it. Set only when the user-facing Decision is the result
    of a platform-error override, so the audit log can surface what
    the policy would have decided otherwise.
    """

    stage: Optional[Stage] = None
    r"""The pipeline component that produced the error. Combined with the
    Type axis on the parent round-trip (Input/Output) and the Offband
    flag, gives the full discrimination of where a platform/upstream
    failure originated. Each value maps to an ownership tier:
    Proofpoint AI Security-owned (Extraction, Analysis, AssignPolicy, AccessPolicy),
    customer-owned (ContentPolicy), provider-owned (Upstream).
    """

    type: Optional[RoundtriperrorType] = None
    r"""The source of the failure. PlatformError covers apex-side stages
    (Extraction, Analysis, ContentPolicy, AccessPolicy). UpstreamError
    covers anything attributable to the upstream provider (transport
    failures or non-2xx HTTP responses).
    """
