"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .alertevent import Alertevent, AlerteventTypedDict
from .destination import Destination, DestinationTypedDict
from .extraction import Extraction, ExtractionTypedDict
from .extractionsummary import Extractionsummary, ExtractionsummaryTypedDict
from .latency import Latency, LatencyTypedDict
from .mcpmessage import Mcpmessage, McpmessageTypedDict
from .principal import Principal, PrincipalTypedDict
from .roundtriperror import Roundtriperror, RoundtriperrorTypedDict
from .tool import Tool, ToolTypedDict
from .toolchoice import Toolchoice, ToolchoiceTypedDict
from .traceref import Traceref, TracerefTypedDict
from acuvity.types import BaseModel
from datetime import datetime
from enum import Enum
import pydantic
from typing import Dict, List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class Decision(str, Enum):
    r"""User-facing outcome of the roundtrip. Reflects the policy
    engine's verdict, or in case of platform failure, the result of the
    failClose strategy (Deny on fail-close, Allow on fail-open, with
    structured error field carring the detail). NotApplicable is
    used by the scan and police APIs, which analyze content without
    rendering an enforcement decision. Error and UpstreamError stay
    in the allowed_choices list for backward compatibility with
    clients that still PUT those values; new round-trips never emit
    them — platform/upstream failures now surface via the structured
    Error field instead.
    NOTE: safe to drop Error and UpstreamError from this enum on or
    after 2026-07-19 (two months after the structured RoundtripError
    landed on 2026-05-19), once consumers have rolled forward.
    """

    DENY = "Deny"
    ALLOW = "Allow"
    ASK = "Ask"
    REPORT = "Report"
    BYPASSED = "Bypassed"
    FORBIDDEN_USER = "ForbiddenUser"
    SKIPPED = "Skipped"
    REDIRECTED = "Redirected"
    NOT_APPLICABLE = "NotApplicable"
    ERROR = "Error"
    UPSTREAM_ERROR = "UpstreamError"


class ProviderType(str, Enum):
    r"""The type of the provider."""

    LLM = "LLM"
    MCP_SERVER = "MCPServer"


class ScanresponseType(str, Enum):
    r"""The type of text."""

    INPUT = "Input"
    OUTPUT = "Output"


class ScanresponseTypedDict(TypedDict):
    r"""This is a scan response."""

    principal: PrincipalTypedDict
    r"""Describe the principal."""
    provider_type: ProviderType
    r"""The type of the provider."""
    id: NotRequired[str]
    r"""ID is the identifier of the object."""
    alerts: NotRequired[List[AlerteventTypedDict]]
    r"""List of alerts that got raised during the policy resolution."""
    annotations: NotRequired[Dict[str, str]]
    r"""Annotations attached to the log."""
    client: NotRequired[str]
    r"""The client used to send the request."""
    client_version: NotRequired[str]
    r"""The version of the client used to send the request."""
    content_redacted: NotRequired[bool]
    r"""If true, the content of the extractions was stripped from the audit entry for
    this request, and only the analysis and other metadata were kept. It reports
    what actually happened, which is not the same as what was requested:
    redactContentBypass can leave the content in place.
    """
    decision: NotRequired[Decision]
    r"""User-facing outcome of the roundtrip. Reflects the policy
    engine's verdict, or in case of platform failure, the result of the
    failClose strategy (Deny on fail-close, Allow on fail-open, with
    structured error field carring the detail). NotApplicable is
    used by the scan and police APIs, which analyze content without
    rendering an enforcement decision. Error and UpstreamError stay
    in the allowed_choices list for backward compatibility with
    clients that still PUT those values; new round-trips never emit
    them — platform/upstream failures now surface via the structured
    Error field instead.
    NOTE: safe to drop Error and UpstreamError from this enum on or
    after 2026-07-19 (two months after the structured RoundtripError
    landed on 2026-05-19), once consumers have rolled forward.
    """
    destination: NotRequired[DestinationTypedDict]
    r"""Represents the destination that this request was made to."""
    error: NotRequired[RoundtriperrorTypedDict]
    r"""Structured error info attached to a roundtrip when a non-user-facing
    platform stage or the upstream provider failed. Carries the platform-side
    detail (type, stage, message) for debugging and provider-health
    derivation. The Decision field still reflects the policy/processing
    outcome per existing semantics.
    """
    extractions: NotRequired[List[ExtractionTypedDict]]
    r"""The extractions to log."""
    hash: NotRequired[str]
    r"""The hash of the input."""
    latency: NotRequired[LatencyTypedDict]
    r"""Holds information about latencies introduced by Apex."""
    mcp_message: NotRequired[McpmessageTypedDict]
    r"""Represents MCP message details."""
    model: NotRequired[str]
    r"""The model used by the request."""
    namespace: NotRequired[str]
    r"""The namespace of the object."""
    pipeline_name: NotRequired[str]
    r"""The name of the particular pipeline that extracted the text."""
    provider: NotRequired[str]
    r"""The provider to use."""
    reasons: NotRequired[List[str]]
    r"""The various reasons returned by the policy engine."""
    summary: NotRequired[ExtractionsummaryTypedDict]
    r"""Represents the summary of the extractions."""
    time: NotRequired[datetime]
    r"""Set the time of the message request."""
    tool_choice: NotRequired[ToolchoiceTypedDict]
    r"""Represents the tool choice that can be passed along together with tools."""
    tools: NotRequired[Dict[str, ToolTypedDict]]
    r"""The various tools used by the request."""
    trace: NotRequired[TracerefTypedDict]
    r"""Holds all references to a trace which are also the essentials of the span data."""
    type: NotRequired[ScanresponseType]
    r"""The type of text."""


class Scanresponse(BaseModel):
    r"""This is a scan response."""

    principal: Principal
    r"""Describe the principal."""

    provider_type: Annotated[ProviderType, pydantic.Field(alias="providerType")]
    r"""The type of the provider."""

    id: Annotated[Optional[str], pydantic.Field(alias="ID")] = None
    r"""ID is the identifier of the object."""

    alerts: Optional[List[Alertevent]] = None
    r"""List of alerts that got raised during the policy resolution."""

    annotations: Optional[Dict[str, str]] = None
    r"""Annotations attached to the log."""

    client: Optional[str] = None
    r"""The client used to send the request."""

    client_version: Annotated[Optional[str], pydantic.Field(alias="clientVersion")] = (
        None
    )
    r"""The version of the client used to send the request."""

    content_redacted: Annotated[
        Optional[bool], pydantic.Field(alias="contentRedacted")
    ] = None
    r"""If true, the content of the extractions was stripped from the audit entry for
    this request, and only the analysis and other metadata were kept. It reports
    what actually happened, which is not the same as what was requested:
    redactContentBypass can leave the content in place.
    """

    decision: Optional[Decision] = None
    r"""User-facing outcome of the roundtrip. Reflects the policy
    engine's verdict, or in case of platform failure, the result of the
    failClose strategy (Deny on fail-close, Allow on fail-open, with
    structured error field carring the detail). NotApplicable is
    used by the scan and police APIs, which analyze content without
    rendering an enforcement decision. Error and UpstreamError stay
    in the allowed_choices list for backward compatibility with
    clients that still PUT those values; new round-trips never emit
    them — platform/upstream failures now surface via the structured
    Error field instead.
    NOTE: safe to drop Error and UpstreamError from this enum on or
    after 2026-07-19 (two months after the structured RoundtripError
    landed on 2026-05-19), once consumers have rolled forward.
    """

    destination: Optional[Destination] = None
    r"""Represents the destination that this request was made to."""

    error: Optional[Roundtriperror] = None
    r"""Structured error info attached to a roundtrip when a non-user-facing
    platform stage or the upstream provider failed. Carries the platform-side
    detail (type, stage, message) for debugging and provider-health
    derivation. The Decision field still reflects the policy/processing
    outcome per existing semantics.
    """

    extractions: Optional[List[Extraction]] = None
    r"""The extractions to log."""

    hash: Optional[str] = None
    r"""The hash of the input."""

    latency: Optional[Latency] = None
    r"""Holds information about latencies introduced by Apex."""

    mcp_message: Annotated[Optional[Mcpmessage], pydantic.Field(alias="mcpMessage")] = (
        None
    )
    r"""Represents MCP message details."""

    model: Optional[str] = None
    r"""The model used by the request."""

    namespace: Optional[str] = None
    r"""The namespace of the object."""

    pipeline_name: Annotated[Optional[str], pydantic.Field(alias="pipelineName")] = None
    r"""The name of the particular pipeline that extracted the text."""

    provider: Optional[str] = None
    r"""The provider to use."""

    reasons: Optional[List[str]] = None
    r"""The various reasons returned by the policy engine."""

    summary: Optional[Extractionsummary] = None
    r"""Represents the summary of the extractions."""

    time: Optional[datetime] = None
    r"""Set the time of the message request."""

    tool_choice: Annotated[Optional[Toolchoice], pydantic.Field(alias="toolChoice")] = (
        None
    )
    r"""Represents the tool choice that can be passed along together with tools."""

    tools: Optional[Dict[str, Tool]] = None
    r"""The various tools used by the request."""

    trace: Optional[Traceref] = None
    r"""Holds all references to a trace which are also the essentials of the span data."""

    type: Optional[ScanresponseType] = None
    r"""The type of text."""
