"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from acuvity.types import BaseModel
import pydantic
from typing import Any, Dict, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class ToolargumentTypedDict(TypedDict):
    r"""Represents a tool input argument."""

    name: str
    r"""The name of the argument."""
    description: NotRequired[str]
    r"""The description of the argument."""
    required: NotRequired[bool]
    r"""Whether this argument is required by the tool."""
    schema_: NotRequired[Dict[str, Any]]
    r"""The JSON schema for this argument, excluding fields promoted to top-level
    attributes.
    """
    type: NotRequired[str]
    r"""The JSON schema type of the argument."""


class Toolargument(BaseModel):
    r"""Represents a tool input argument."""

    name: str
    r"""The name of the argument."""

    description: Optional[str] = None
    r"""The description of the argument."""

    required: Optional[bool] = None
    r"""Whether this argument is required by the tool."""

    schema_: Annotated[Optional[Dict[str, Any]], pydantic.Field(alias="schema")] = None
    r"""The JSON schema for this argument, excluding fields promoted to top-level
    attributes.
    """

    type: Optional[str] = None
    r"""The JSON schema type of the argument."""
