guardrails:
  - name: prompt_injection
    threshold: ">= 0.7"
  - name: malicious_url
    threshold: ">= 0.7"
  - name: toxic
    threshold: "0.7"
  - name: jailbreak
    threshold: ">= 1.0"
  - name: biased
    threshold: "0.8"
  - name: harmful
    threshold: "0.8"
  - name: language
    matches:
      chinese:
      english:
      french:
      german:
      japanese:
      russian:
      spanish:
      gibberish:
  - name: pii_detector
    matches:
      # example: Optional redact: true, default redact: False
      email_address:
        redact: true
      ssn:
        redact: true
      person:
        redact: true
      # all possible PIIs (redact default False)
      aba_routing_number:
      address:
      bank_account:
      bitcoin_wallet:
      credit_card:
      driver_license:
      itin_number:
      location:
      medical_license:
      money_amount:
      passport_number:
      phone_number:
  - name: secrets_detector
    matches:
      # example Optional redact: true, default redact: False
      credentials:
        redact: true
      # all possible secrets (redact default False)
      adafruit:
      alibaba:
      anthropic:
      apideck:
      apify:
      atlassian:
      aws_secret_key:
      buildkite:
      checkout:
      clickuppersonal:
      contentfulpersonalaccess:
      database_url_with_credentials:
      databricks:
      denodeploy:
      dfuse:
      digitalocean:
      discord_webhook:
      docker_hub:
      doppler:
      dropbox:
      endorlabs:
      fleetbase:
      flutterwave:
      frameio:
      freshdesk:
      fullstory:
      github:
      gitlab:
      gocardless:
      google_api:
      grafana:
      groq:
      huggingface:
      intra42:
      jwt:
      klaviyo:
      launchdarkly:
      linearapi:
      locationiq:
      mailchimp:
      mailgun:
      mapbox:
      maxmind:
      microsoft_teams_webhook:
      nightfall:
      notion:
      npm:
      openai:
      pagarme:
      paystack:
      planetscale:
      planetscaledb:
      portainer:
      posthog:
      postman:
      prefect:
      private_key:
      pubnub_publish:
      pubnub_subscribe:
      pulumi:
      ramp:
      razorpay:
      readme:
      rechargepayments:
      replicate:
      rubygems:
      salesforce:
      sendgrid:
      sendinblue:
      shopify:
      slack_access:
      slack_bot:
      slack_refresh:
      slack_user:
      slack_webhook:
      slack_workflow_webhook:
      sourcegraph:
      sourcegraphcody:
      squareapp:
      squareup:
      stripe:
      supabase:
      tailscale:
      tines_webhook:
      trufflehog:
      twilio:
      ubidots:
      voiceflow:
      web_url_with_credentials:
      zapierwebhook:
