# This runs on
# - Push to main
# - PRs
name: test
on:
  push:
    branches:
      - main
  pull_request:
    inputs:
      platform:
        description: 'Which platform to target'
        required: true
        default: "prod"
        type: choice
        options:
          - prod
          - pre_prod
          - dev
  workflow_dispatch:
    inputs:
      platform:
        description: 'Which platform to target'
        required: true
        default: "prod"
        type: choice
        options:
          - prod
          - pre_prod
          - dev

defaults:
  run:
    shell: bash

env:
  ACUVITY_TOKEN: ${{ secrets.ACUVITY_TOKEN }}
  APPS_DEV_TOKEN: ${{ secrets.APPS_DEV_TOKEN }}
  APPS_PRE_PROD_TOKEN: ${{ secrets.APPS_PRE_PROD_TOKEN }}
  APPS_PROD_TOKEN: ${{ secrets.APPS_PROD_TOKEN }}

jobs:
  sanity:
    name: Sanity
    runs-on: ubuntu-latest
    concurrency:
      group: matrix-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: |
          touch README-PYPI.md
          pip install -e .
          pip install pytest

      - name: Run examples
        run: |
          pip install rich
          echo "Running all examples ..."
          ./examples/run.sh

      - name: Pytest e2e tests
        run: |
          echo "Running e2e tests ..."
          pip install pytest
          pip install pytest-subtests
          pytest ./tests/e2e --platform ${{ inputs.platform }}

      - name: Pytest unit tests
        run: |
          echo "Running unit tests ..."
          pip install pytest
          pytest ./tests/guard 
          pytest ./tests/response

        

